name: Build Packages

on:
  # Manual trigger
  workflow_dispatch:

  # Trigger on commits to main
  push:
    branches: [ main ]

  # Trigger on pull requests
  pull_request:

jobs:
  linux-amd64:
    runs-on: ${{ ubuntu-22.04 }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Build deb and rpm
        run: ./gradlew clean deb rpm

      - name: Prepare Linux artifacts (flatten)
        run: |
          mkdir -p temp-artifacts/linux-packages-amd64
          find . -type f -name "*.deb" -exec cp {} temp-artifacts/linux-packages-amd64 \;
          find . -type f -name "*.rpm" -exec cp {} temp-artifacts/linux-packages-amd64 \;

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages-amd64
          path: temp-artifacts/*

  linux-arm64:
    runs-on: ${{ ubuntu-22.04 }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build inside arm64 container
        run: |
          docker run --rm --platform=linux/arm64 \
          -v $PWD -w /workspace \
          ghcr.io/graalvm/jdk-community:24 \
          bash -c "
          cd /workspace \
          chmod +x gradlew \
          ./gradlew clean deb rpm

      - name: Prepare Linux artifacts (flatten)
        run: |
          mkdir -p temp-artifacts/linux-packages-arm64
          find . -type f -name "*.deb" -exec cp {} temp-artifacts/linux-packages-arm64 \;
          find . -type f -name "*.rpm" -exec cp {} temp-artifacts/linux-packages-arm64 \;

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages-arm64
          path: temp-artifacts/*

  macos-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Build macOS app zip
        run: ./gradlew clean generateBrewFormulaLocal

      - name: Prepare macOS artifact (flatten)
        run: |
          mkdir -p temp-artifacts/macos-app
          find . -type f -name "*-mac*.tar.gz" -exec cp {} temp-artifacts/macos-app/ \;
          find . -type f -name "divyam-cli*.rb" -exec cp {} temp-artifacts/macos-app/ \;

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-apple-silicon
          path: temp-artifacts/*

  macos-amd64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Build macOS app zip
        run: ./gradlew clean generateBrewFormulaLocal

      - name: Prepare macOS artifact (flatten)
        run: |
          mkdir -p temp-artifacts/macos-app
          find . -type f -name "*-mac*.tar.gz" -exec cp {} temp-artifacts/macos-app/ \;
          find . -type f -name "divyam-cli*.rb" -exec cp {} temp-artifacts/macos-app/ \;

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64
          path: temp-artifacts/*
